In [1]:
import pandas as pd
path = r"E:\OneDrive\_workflow\binding of issac FLASH item description\recog_test2\dataset"
path = r".\dataset"
df_list = (pd.read_csv(f) for f in [path+r'\1.csv', path+r'.\2.csv', path+r'.\3.csv', path+r'.\4.csv'])
combined_df = pd.concat(df_list, ignore_index=True)
combined_df = combined_df.rename(columns={"isReload": "reloadCnt", "descr":"descrRU"})
combined_df.head()
display(combined_df.head())
display(combined_df.describe())

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath
0,Поваренная книга анархиста,Anarchist Cookbook,https://static.wikia.nocookie.net/bindingofisa...,В пределах комнаты создаёт 6 тролль-бомб в слу...,065_TBoI_collectibles.png,3,False,False
1,Боб,The Bean,https://static.wikia.nocookie.net/bindingofisa...,При активации наносит ближайшим врагам 5 едини...,111_TBoI_collectibles.png,1,False,False
2,Гнилая голова Боба,Bob’s Rotten Head,https://static.wikia.nocookie.net/bindingofisa...,При активации герой поднимает над собой голову...,042_TBoI_collectibles.png,3,False,False
3,Библия,The Bible,https://static.wikia.nocookie.net/bindingofisa...,Дарует крылья и возможность летать в пределах ...,033_TBoI_collectibles.png,6,False,False
4,Книга Белиала,The Book of Belial,https://static.wikia.nocookie.net/bindingofisa...,Артефакт даёт +2 к урону в пределах одной комн...,034_TBoI_collectibles.png,3,False,False

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath
count,196,196,196,196,196,52,196,196
unique,196,196,196,191,196,13,2,2
top,Поваренная книга анархиста,Anarchist Cookbook,https://static.wikia.nocookie.net/bindingofisa...,Даёт один полный контейнер здоровья.,065_TBoI_collectibles.png,6,True,False
freq,1,1,1,3,1,10,144,130

In [2]:
combined_df['imgName'] = combined_df.apply(lambda x: x['imgName'].replace('.png','.webp'), axis = 1)    
combined_df['isTrinket'] = False
#combined_df["urlToPage"] = ''
combined_df["imgSrc_dataset"] = ".\dataset\itemsImgs" + '\\' + combined_df["imgName"]
combined_df.head()

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\m\AppData\Local\Temp\ipykernel_10736\1110713247.py:4: SyntaxWarning: invalid escape sequence '\d'
  combined_df["imgSrc_dataset"] = ".\dataset\itemsImgs" + '\\' + combined_df["imgName"]

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath,isTrinket,imgSrc_dataset
0,Поваренная книга анархиста,Anarchist Cookbook,https://static.wikia.nocookie.net/bindingofisa...,В пределах комнаты создаёт 6 тролль-бомб в слу...,065_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\065_TBoI_collectibles.webp
1,Боб,The Bean,https://static.wikia.nocookie.net/bindingofisa...,При активации наносит ближайшим врагам 5 едини...,111_TBoI_collectibles.webp,1,False,False,False,.\dataset\itemsImgs\111_TBoI_collectibles.webp
2,Гнилая голова Боба,Bob’s Rotten Head,https://static.wikia.nocookie.net/bindingofisa...,При активации герой поднимает над собой голову...,042_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\042_TBoI_collectibles.webp
3,Библия,The Bible,https://static.wikia.nocookie.net/bindingofisa...,Дарует крылья и возможность летать в пределах ...,033_TBoI_collectibles.webp,6,False,False,False,.\dataset\itemsImgs\033_TBoI_collectibles.webp
4,Книга Белиала,The Book of Belial,https://static.wikia.nocookie.net/bindingofisa...,Артефакт даёт +2 к урону в пределах одной комн...,034_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\034_TBoI_collectibles.webp

In [3]:
trinkets_df = pd.read_csv(path+r'\5.csv')
#combined_df = pd.concat([combined_df, trinkets_df], ignore_index=True)
#display(trinkets_df.head())
#display(trinkets_df.describe())
trinkets_df["imgSrc_dataset"] = ".\dataset\itemsImgs" + '\\' + trinkets_df["imgName"]
trinkets_df = trinkets_df.rename(columns={"descr":"descrRU"})
#pd.set_option('display.max_columns', 1500)
trinkets_df = trinkets_df.drop('urlToPage', axis=1)
display(trinkets_df[["nameEN","imgName","imgSrc","descrRU"]])

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
C:\Users\m\AppData\Local\Temp\ipykernel_10736\998784664.py:5: SyntaxWarning: invalid escape sequence '\d'
  trinkets_df["imgSrc_dataset"] = ".\dataset\itemsImgs" + '\\' + trinkets_df["imgName"]

,nameEN,imgName,imgSrc,descrRU
0,???'s Soul,3F3F.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Спутник. Медленно летает по комнате по диагона...
1,Ace of Spades,ТузПик.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает вероятность выпадения карт Таро.
2,Bloody Penny,101px-Bloodypenny.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт шанс выпадения половины красного сердца п...
3,Burnt Penny,80px-Burntpenny.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт шанс выпадения бомбы при сборе монет.
4,Cain's Eye,ГлазКаина.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт вероятность получения эффекта Компаса на ...
5,Cancer,Undefined.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает скорострельность в два раза.
6,Child's Heart,СердцеРебенка.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает количество выпадающих сердец.
7,Counterfeit Penny,Counterfeitpenny.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Подобранная монета может быть на один пенни вы...
8,Cursed Skull,ПроклятыйЧереп.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Как только здоровье снижается до половины серд...
9,Curved Horn,Curvedhorn.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает урон на 2 вне формулы.
10,Eve's Bird Foot,ПтичьяЛапкаЕвы.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт вероятность появления спутника-мёртвой пт...
11,Flat Penny,Flattenedpenny.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт шанс (50%) выпадения ключа при сборе монет.
12,Fish Head,Рыбьяголова.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Атакующая муха появляется при нанесении урона ...
13,Goat Hoof,Goathoof.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает скорость передвижения.
14,Isaac's Head,ГоловаИсаака.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Спутник-голова Исаака. Стреляет пронизывающими...
15,Isaacs Fork,ВилкаИсаака.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт вероятность (10%) получения половины серд...
16,Judas's Tongue,ЯзыкИуды.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Сделки с Дьяволом стоят меньше: предметы за 2 ...
17,The Left Hand,ЛеваяРука.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Заменяет обычные и золотые сундуки на красные.
18,Liberty Cap,ШляпкаСвободы.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,При входе в комнаты персонаж с вероятностью в ...
19,Lucky Toe,Luckytoe.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает вероятность появления подбираемых ...
20,Maggy's Faith,ВераМэгги.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт вечное сердце в начале каждого уровня.
21,Match Stick,Matchstick.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает шанс выпадения бомб.
22,A Missing Page,Аз.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,При получении урона есть вероятность срабатыва...
23,Mom's Pearl,Momspearl.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает шанс замены красного сердца на син...
24,Pinky Eye,РозовыйГлаз.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Даёт шанс выстрелить отравленной слезой.
25,The Polaroid,Thepolaroid.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,При падении здоровья до половины сердца появля...
26,Push Pin,КанцКнопка.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,С некоторой вероятностью накладывает на выстре...
27,Red Patch,КраснаяЗаплатка.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Имеет вероятность тройного срабатывания эффект...
28,Rusted Key,РжавыйКлюч.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает шанс выпадения ключей и золотых су...
29,Safety Cap,Каска.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Увеличивает вероятность выпадения пилюль.
30,Samson's Lock,ЛоконСамсона.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,С шансом 1 к 15 за убийство врага увеличиваетс...
31,The Tick,Tickhirez.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Боссы появляются со сниженным здоровьем. Нельз...
32,Umbilical Cord,Umbilicalcord.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,"Когда остаётся половина красного сердца, появл..."
33,Game Squid,Game_Squid.webp,./Брелоки (Flash) _ The Binding of Isaac вики ...,Слезы персонажа с некоторой вероятностью стано...

In [4]:
#join trinket and items
all_df = pd.concat([combined_df, trinkets_df], ignore_index=True)
display(all_df.head())
display(all_df.describe())
#asd_df.to_excel('dataset.xlsx')
#all_df.to_csv('dataset.csv')

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath,isTrinket,imgSrc_dataset
0,Поваренная книга анархиста,Anarchist Cookbook,https://static.wikia.nocookie.net/bindingofisa...,В пределах комнаты создаёт 6 тролль-бомб в слу...,065_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\065_TBoI_collectibles.webp
1,Боб,The Bean,https://static.wikia.nocookie.net/bindingofisa...,При активации наносит ближайшим врагам 5 едини...,111_TBoI_collectibles.webp,1,False,False,False,.\dataset\itemsImgs\111_TBoI_collectibles.webp
2,Гнилая голова Боба,Bob’s Rotten Head,https://static.wikia.nocookie.net/bindingofisa...,При активации герой поднимает над собой голову...,042_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\042_TBoI_collectibles.webp
3,Библия,The Bible,https://static.wikia.nocookie.net/bindingofisa...,Дарует крылья и возможность летать в пределах ...,033_TBoI_collectibles.webp,6,False,False,False,.\dataset\itemsImgs\033_TBoI_collectibles.webp
4,Книга Белиала,The Book of Belial,https://static.wikia.nocookie.net/bindingofisa...,Артефакт даёт +2 к урону в пределах одной комн...,034_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\034_TBoI_collectibles.webp

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath,isTrinket,imgSrc_dataset
count,230,230,230,230,230,86,230,230,230,230
unique,230,230,230,225,230,14,2,2,2,230
top,Поваренная книга анархиста,Anarchist Cookbook,https://static.wikia.nocookie.net/bindingofisa...,Даёт один полный контейнер здоровья.,065_TBoI_collectibles.webp,-1,True,False,False,.\dataset\itemsImgs\065_TBoI_collectibles.webp
freq,1,1,1,3,1,34,178,130,196,1

In [5]:
import numpy as np
def linebreaker(row):
    if(pd.isna(row)):
        return np.nan
    return row.replace('\r\n','<br>')
all_df2 = all_df
all_df2["descrRU"] = all_df2.apply(lambda x: linebreaker(x["descrRU"]), axis=1)

In [6]:
#add new cols
all_df2["descrEN_trans"] = pd.read_csv(r".\dataset\descrEN.csv", dtype = 'string')["descrEN_trans"]
all_df2["descrEN_trans"] = all_df.apply(lambda x: linebreaker(x["descrEN_trans"]), axis=1)
all_df2["urlToPageRU"] = pd.read_csv(r".\dataset\urlToPageRU.csv", dtype = 'string')["urlToPageRU"]

#all_df2.to_csv('dataset.csv')
all_df2.head()

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath,isTrinket,imgSrc_dataset,descrEN_trans,urlToPageRU
0,Поваренная книга анархиста,Anarchist Cookbook,https://static.wikia.nocookie.net/bindingofisa...,В пределах комнаты создаёт 6 тролль-бомб в слу...,065_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\065_TBoI_collectibles.webp,Creates 6 troll bombs in random locations with...,/ru/wiki/%D0%9F%D0%BE%D0%B2%D0%B0%D1%80%D0%B5%...
1,Боб,The Bean,https://static.wikia.nocookie.net/bindingofisa...,При активации наносит ближайшим врагам 5 едини...,111_TBoI_collectibles.webp,1,False,False,False,.\dataset\itemsImgs\111_TBoI_collectibles.webp,When activated; deals 5 damage to nearby enemi...,/ru/wiki/%D0%91%D0%BE%D0%B1#Flash
2,Гнилая голова Боба,Bob’s Rotten Head,https://static.wikia.nocookie.net/bindingofisa...,При активации герой поднимает над собой голову...,042_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\042_TBoI_collectibles.webp,When activated; the hero raises his head above...,/ru/wiki/%D0%93%D0%BD%D0%B8%D0%BB%D0%B0%D1%8F_...
3,Библия,The Bible,https://static.wikia.nocookie.net/bindingofisa...,Дарует крылья и возможность летать в пределах ...,033_TBoI_collectibles.webp,6,False,False,False,.\dataset\itemsImgs\033_TBoI_collectibles.webp,Grants wings and the ability to fly within the...,/ru/wiki/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D1%8F#...
4,Книга Белиала,The Book of Belial,https://static.wikia.nocookie.net/bindingofisa...,Артефакт даёт +2 к урону в пределах одной комн...,034_TBoI_collectibles.webp,3,False,False,False,.\dataset\itemsImgs\034_TBoI_collectibles.webp,The artifact provides +2 damage within a singl...,/ru/wiki/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0_%D0%91...

In [7]:
#filter 3 row - trinket and not trinket
'''
df_filtered = (
    asd_df[asd_df['isTrinket'].isin([True, False])]
    .groupby('isTrinket', as_index =True)
    .apply(lambda x: x.sample(n=3)
    #.unstack()
    #.reset_index(drop=True) #reset index col - isTrinket . здесь почемуто не работает
          )
)
display(df_filtered.reset_index())
'''

"\ndf_filtered = (\n    asd_df[asd_df['isTrinket'].isin([True, False])]\n    .groupby('isTrinket', as_index =True)\n    .apply(lambda x: x.sample(n=3)\n    #.unstack()\n    #.reset_index(drop=True) #reset index col - isTrinket . здесь почемуто не работает\n          )\n)\ndisplay(df_filtered.reset_index())\n"

In [16]:
#filter test
#res = all_df2.loc[all_df2['nameEN'] == 'Little C.H.A.D.']
res = all_df2.loc[all_df2['nameEN'] == 'Little C.H.A.D.']
#res = all_df2.iloc[60]
display(res)

,nameRU,nameEN,imgSrc,descrRU,imgName,reloadCnt,isPassive,isWrath,isTrinket,imgSrc_dataset,descrEN_trans,urlToPageRU
60,Маленький Ч.А.Д.,Little C.H.A.D.,https://static.wikia.nocookie.net/bindingofisa...,Следует за игроком и создает пол-сердца после ...,096_TBoI_collectibles.webp,NaN,True,False,False,.\dataset\itemsImgs\096_TBoI_collectibles.webp,Follows the player and creates half a heart af...,/ru/wiki/%D0%9C%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%...